build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Shan - Developer"
    email: "shan@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1243
