build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Aish - Developer"
    email: "aish@eazybank.com"
  onCallSupport:
    - (666) 666-1234
    - (666) 666-1243